In [11]:
import pandas as pd
import psycopg2
from sqlalchemy import create_engine

In [12]:
def get_connection():
    try:
        conn = psycopg2.connect(
            host="localhost",
            database="amazon_ecommerce",
            user="postgres",
            password="280402",
            port="5432"
        )
        print("PostgreSQL Connection Successful ✅")
        return conn
    except Exception as e:
        print(f"Connection failed: {e}")
        return None

conn = get_connection()
cursor = conn.cursor()

PostgreSQL Connection Successful ✅

In [13]:
engine = create_engine(
    "postgresql+psycopg2://postgres:280402@localhost:5432/amazon_ecommerce"
)

In [15]:
df = pd.read_csv("../../Data/processed_datasets/amazon_full_cleaned.csv")

df.head()

,customer_state,final_amount_inr,payment_method,delivery_charges,quantity,order_month,delivery_days,order_date,customer_id,transaction_id,...,subcategory,customer_city,order_quarter,order_year,delivery_type,original_price_inr,festival_name,brand,category,customer_spending_tier
0,Maharashtra,89112.17,COD,0.0,1,1,6,2015-01-25,CUST_2015_00003884,TXN_2015_00000001,...,Smartphones,Mumbai,1,2015,Standard,123614.29,Republic Day Sale,Samsung,Electronics,Premium
1,Uttar Pradesh,54731.86,COD,0.0,1,1,4,2015-01-05,CUST_2015_00011709,TXN_2015_00000002,...,Smartphones,Allahabad,1,2015,Standard,54731.86,No Festival,OnePlus,Electronics,Standard
2,Maharashtra,103636.52,COD,0.0,2,1,4,2015-01-24,CUST_2015_00004782,TXN_2015_00000003,...,Smartphones,Mumbai,1,2015,Standard,97644.25,Republic Day Sale,Samsung,Electronics,Premium
3,West Bengal,21947.26,COD,0.0,1,1,4,2015-01-28,CUST_2015_00008105,TXN_2015_00000004,...,Smartphones,Kolkata,1,2015,Standard,21947.26,No Festival,Motorola,Electronics,Budget
4,Punjab,109463.72,COD,0.0,2,1,3,2015-01-31,CUST_2015_00002955,TXN_2015_00000005,...,Smartphones,Ludhiana,1,2015,Standard,54731.86,No Festival,OnePlus,Electronics,Standard

### Basic Processing

In [16]:
df['order_date'] = pd.to_datetime(df['order_date'], errors='coerce')

### Create Tables

Drop Tables

Create Tables

In [18]:
cursor.execute("""
CREATE TABLE products (
    product_id TEXT PRIMARY KEY,
    product_name TEXT,
    category TEXT,
    subcategory TEXT,
    brand TEXT,
    product_rating FLOAT
);

CREATE TABLE customers (
    customer_id TEXT PRIMARY KEY,
    customer_city TEXT,
    customer_state TEXT,
    age_group TEXT,
    is_prime_member BOOLEAN
);

CREATE TABLE time_dimension (
    order_date DATE PRIMARY KEY,
    year INT,
    month INT,
    day INT,
    quarter INT
);

CREATE TABLE transactions (
    transaction_id TEXT PRIMARY KEY,
    customer_id TEXT,
    product_id TEXT,
    order_date DATE,
    final_amount_inr FLOAT,
    payment_method TEXT,
    delivery_days INT,
    return_status TEXT,
    customer_rating FLOAT,
    is_festival_sale BOOLEAN,
    
    FOREIGN KEY (customer_id) REFERENCES customers(customer_id),
    FOREIGN KEY (product_id) REFERENCES products(product_id),
    FOREIGN KEY (order_date) REFERENCES time_dimension(order_date)
);
""")

conn.commit()

### Insert Data

Products

In [19]:
products = df[[
    'product_id', 'product_name', 'category',
    'subcategory', 'brand', 'product_rating'
]].drop_duplicates()

products.to_sql("products", engine, if_exists='append', index=False)

4

Customers

In [21]:
df.columns.tolist()

['customer_state',
 'final_amount_inr',
 'payment_method',
 'delivery_charges',
 'quantity',
 'order_month',
 'delivery_days',
 'order_date',
 'customer_id',
 'transaction_id',
 'subtotal_inr',
 'product_weight_kg',
 'customer_age_group',
 'return_status',
 'product_name',
 'is_festival_sale',
 'customer_rating',
 'is_prime_member',
 'discounted_price_inr',
 'discount_percent',
 'is_prime_eligible',
 'product_rating',
 'customer_tier',
 'product_id',
 'subcategory',
 'customer_city',
 'order_quarter',
 'order_year',
 'delivery_type',
 'original_price_inr',
 'festival_name',
 'brand',
 'category',
 'customer_spending_tier']

In [22]:
customers = df[[
    'customer_id', 'customer_city',
    'customer_state', 'customer_age_group',
    'is_prime_member'
]].drop_duplicates()

In [23]:
customers = df[[
    'customer_id',
    'customer_city',
    'customer_state',
    'customer_age_group',
    'customer_tier',
    'customer_spending_tier',
    'is_prime_member'
]].drop_duplicates()

In [28]:
cursor.execute("""
DROP TABLE IF EXISTS products CASCADE;

CREATE TABLE products (
    product_id TEXT PRIMARY KEY,
    product_name TEXT,
    category TEXT,
    subcategory TEXT,
    brand TEXT,
    product_rating FLOAT,
    is_prime_eligible BOOLEAN,
    product_weight_kg FLOAT
);
""")

conn.commit()

print("Products table recreated ✅")

Products table recreated ✅

In [29]:
products.to_sql("products", engine, if_exists='append', index=False)

print("Products data inserted ✅")

Products data inserted ✅

In [30]:
print(df.columns)

Index(['customer_state', 'final_amount_inr', 'payment_method',
       'delivery_charges', 'quantity', 'order_month', 'delivery_days',
       'order_date', 'customer_id', 'transaction_id', 'subtotal_inr',
       'product_weight_kg', 'customer_age_group', 'return_status',
       'product_name', 'is_festival_sale', 'customer_rating',
       'is_prime_member', 'discounted_price_inr', 'discount_percent',
       'is_prime_eligible', 'product_rating', 'customer_tier', 'product_id',
       'subcategory', 'customer_city', 'order_quarter', 'order_year',
       'delivery_type', 'original_price_inr', 'festival_name', 'brand',
       'category', 'customer_spending_tier'],
      dtype='object')

Customers

In [34]:
cursor.execute("""
CREATE TABLE customers (
    customer_id TEXT PRIMARY KEY,
    customer_city TEXT,
    customer_state TEXT,
    customer_age_group TEXT,
    customer_tier TEXT,
    customer_spending_tier TEXT,
    is_prime_member BOOLEAN
);
""")

Time Dimensions

In [35]:
cursor.execute("""
CREATE TABLE time_dimension (
    order_date DATE PRIMARY KEY,
    order_month INT,
    order_quarter INT,
    order_year INT
);
""")

Trasactions

In [36]:
cursor.execute("""
CREATE TABLE transactions (
    transaction_id TEXT PRIMARY KEY,
    customer_id TEXT,
    product_id TEXT,
    order_date DATE,

    original_price_inr FLOAT,
    discounted_price_inr FLOAT,
    discount_percent FLOAT,
    final_amount_inr FLOAT,
    subtotal_inr FLOAT,
    delivery_charges FLOAT,

    quantity INT,
    payment_method TEXT,
    delivery_days INT,
    delivery_type TEXT,

    customer_rating FLOAT,
    return_status TEXT,

    is_festival_sale BOOLEAN,
    festival_name TEXT,

    FOREIGN KEY (customer_id) REFERENCES customers(customer_id),
    FOREIGN KEY (product_id) REFERENCES products(product_id),
    FOREIGN KEY (order_date) REFERENCES time_dimension(order_date)
);
""")

conn.commit()

print("All tables created ✅")

All tables created ✅

### Inserting Data

Products

In [48]:
cursor.execute("TRUNCATE TABLE products CASCADE;")
conn.commit()

print("Products table cleared ✅")

Products table cleared ✅

In [49]:
products = df[[
    'product_id',
    'product_name',
    'category',
    'subcategory',
    'brand',
    'product_rating',
    'is_prime_eligible',
    'product_weight_kg'
]].drop_duplicates(subset='product_id')

In [50]:
products.to_sql("products", engine, if_exists='append', index=False)

print("Products inserted successfully ✅")

Products inserted successfully ✅

Customers

In [52]:
cursor.execute("TRUNCATE TABLE customers CASCADE;")
conn.commit()

In [53]:
customers = df[[
    'customer_id',
    'customer_city',
    'customer_state',
    'customer_age_group',
    'customer_tier',
    'customer_spending_tier',
    'is_prime_member'
]].drop_duplicates(subset='customer_id')

In [54]:
customers.to_sql("customers", engine, if_exists='append', index=False)

print("Customers loaded ✅")

Customers loaded ✅

### Time Dimension

Clear Table

In [55]:
cursor.execute("TRUNCATE TABLE time_dimension CASCADE;")
conn.commit()

Deduplicate correctly

In [56]:
time_dim = df[[
    'order_date',
    'order_month',
    'order_quarter',
    'order_year'
]].drop_duplicates(subset='order_date')

Insert

In [57]:
time_dim.to_sql("time_dimension", engine, if_exists='append', index=False)

print("Time dimension loaded ✅")

Time dimension loaded ✅

### Transactions Table

Clear Table

In [58]:
cursor.execute("TRUNCATE TABLE transactions CASCADE;")
conn.commit()

Prepare Data

In [59]:
transactions = df[[
    'transaction_id',
    'customer_id',
    'product_id',
    'order_date',

    'original_price_inr',
    'discounted_price_inr',
    'discount_percent',
    'final_amount_inr',
    'subtotal_inr',
    'delivery_charges',

    'quantity',
    'payment_method',
    'delivery_days',
    'delivery_type',

    'customer_rating',
    'return_status',

    'is_festival_sale',
    'festival_name'
]]

Insert

In [60]:
transactions.to_sql("transactions", engine, if_exists='append', index=False)

print("Transactions loaded ✅")

Transactions loaded ✅

Indexes

In [61]:
cursor.execute("""
CREATE INDEX IF NOT EXISTS idx_customer_id ON transactions(customer_id);
CREATE INDEX IF NOT EXISTS idx_product_id ON transactions(product_id);
CREATE INDEX IF NOT EXISTS idx_order_date ON transactions(order_date);
""")

conn.commit()

print("Indexes created ✅")

Indexes created ✅

In [62]:
pd.read_sql("SELECT COUNT(*) FROM transactions;", engine)

     count
0  1127609

Database Verification

Verify Constraints

In [64]:
pd.read_sql("""
SELECT conname, conrelid::regclass AS table_name
FROM pg_constraint
WHERE contype = 'p';
""", engine)

                                      conname           table_name
0                           pg_proc_oid_index              pg_proc
1                           pg_type_oid_index              pg_type
2             pg_attribute_relid_attnum_index         pg_attribute
3                          pg_class_oid_index             pg_class
4                        pg_attrdef_oid_index           pg_attrdef
..                                        ...                  ...
61  pg_subscription_rel_srrelid_srsubid_index  pg_subscription_rel
62                              products_pkey             products
63                             customers_pkey            customers
64                        time_dimension_pkey       time_dimension
65                          transactions_pkey         transactions

[66 rows x 2 columns]