In [1]:
import pandas as pd
import psycopg2
from sqlalchemy import create_engine

In [2]:
# Connection
conn = psycopg2.connect(
    host="localhost",
    database="amazon_ecommerce",
    user="postgres",
    password="280402",
    port="5432"
)

engine = create_engine(
    "postgresql+psycopg2://postgres:280402@localhost:5432/amazon_ecommerce"
)

### 1. Total Revenue

In [3]:
query = "SELECT SUM(final_amount_inr) AS total_revenue FROM transactions;"
pd.read_sql(query, engine)

   total_revenue
0   7.688873e+10

### 2. Revenue Trend

In [4]:
query = """
SELECT td.order_year, SUM(t.final_amount_inr) AS revenue
FROM transactions t
JOIN time_dimension td ON t.order_date = td.order_date
GROUP BY td.order_year
ORDER BY td.order_year;
"""
pd.read_sql(query, engine)

    order_year       revenue
0         2015  2.142163e+09
1         2016  3.598316e+09
2         2017  5.510026e+09
3         2018  7.248545e+09
4         2019  8.605901e+09
5         2020  1.187319e+10
6         2021  1.099021e+10
7         2022  8.532312e+09
8         2023  7.712999e+09
9         2024  6.823413e+09
10        2025  3.851650e+09

### 3. Monthly Sales Trend

In [5]:
query = """
SELECT td.order_year, td.order_month, 
       SUM(t.final_amount_inr) AS revenue
FROM transactions t
JOIN time_dimension td ON t.order_date = td.order_date
GROUP BY td.order_year, td.order_month
ORDER BY td.order_year, td.order_month;
"""
pd.read_sql(query, engine)

     order_year  order_month       revenue
0          2015            1  2.231943e+08
1          2015            2  1.939797e+08
2          2015            3  1.856119e+08
3          2015            4  2.052414e+08
4          2015            5  1.888309e+08
..          ...          ...           ...
127        2025            8  3.066279e+08
128        2025            9  2.551984e+08
129        2025           10  2.463483e+08
130        2025           11  2.761263e+08
131        2025           12  3.349815e+08

[132 rows x 3 columns]

### 4. Top 10 Products

In [6]:
query = """
SELECT p.product_name, SUM(t.final_amount_inr) AS revenue
FROM transactions t
JOIN products p ON t.product_id = p.product_id
GROUP BY p.product_name
ORDER BY revenue DESC
LIMIT 10;
"""
pd.read_sql(query, engine)

                        product_name       revenue
0       Samsung Galaxy S6 16GB Black  3.243214e+08
1          Apple iPhone 6 64GB Black  3.038824e+08
2  Alienware Ultrabook 4GB RAM Black  2.791681e+08
3        ASUS Inspiron 4GB RAM Black  2.533582e+08
4          Apple iPhone 8 64GB Black  2.437773e+08
5         Apple iPhone SE 32GB Black  2.434699e+08
6       OnePlus OnePlus 2 32GB Black  2.417118e+08
7          Apple iPhone 6 32GB White  2.416709e+08
8  Samsung Galaxy S6 Edge 16GB White  2.341719e+08
9           Apple iPhone 8 16GB Blue  2.338168e+08

### 5. Category Performance

In [7]:
query = """
SELECT p.category, SUM(t.final_amount_inr) AS revenue
FROM transactions t
JOIN products p ON t.product_id = p.product_id
GROUP BY p.category
ORDER BY revenue DESC;
"""
pd.read_sql(query, engine)

      category       revenue
0  Electronics  7.688873e+10

### 6. Customer Segmentation

In [8]:
query = """
SELECT c.customer_spending_tier, 
       SUM(t.final_amount_inr) AS revenue
FROM transactions t
JOIN customers c ON t.customer_id = c.customer_id
GROUP BY c.customer_spending_tier
ORDER BY revenue DESC;
"""
pd.read_sql(query, engine)

  customer_spending_tier       revenue
0               Standard  4.231004e+10
1                Premium  2.756674e+10
2                 Budget  7.011950e+09

### 7. Prime vs Non-Prime Analysis

In [9]:
query = """
SELECT c.is_prime_member, 
       COUNT(*) AS orders,
       AVG(t.final_amount_inr) AS avg_order_value
FROM transactions t
JOIN customers c ON t.customer_id = c.customer_id
GROUP BY c.is_prime_member;
"""
pd.read_sql(query, engine)

   is_prime_member  orders  avg_order_value
0            False  698485     62034.145333
1             True  429124     78203.059163

### 8. Payment Method Analysis

In [10]:
query = """
SELECT payment_method, COUNT(*) AS usage_count
FROM transactions
GROUP BY payment_method
ORDER BY usage_count DESC;
"""
pd.read_sql(query, engine)

  payment_method  usage_count
0            UPI       384228
1            COD       322831
2    Credit Card       172261
3     Debit Card       140202
4    Net Banking        64971
5         Wallet        22821
6           BNPL        20295

### 9. Delivery Performance

In [11]:
query = """
SELECT AVG(delivery_days) AS avg_delivery_days
FROM transactions;
"""
pd.read_sql(query, engine)

   avg_delivery_days
0           3.333039

### 10. Festival Sales Impact

In [12]:
query = """
SELECT is_festival_sale, 
       SUM(final_amount_inr) AS revenue
FROM transactions
GROUP BY is_festival_sale;
"""
pd.read_sql(query, engine)

   is_festival_sale       revenue
0             False  6.027034e+10
1              True  1.661839e+10

### 11. Delivery Perormance by City

In [13]:
query = """
SELECT c.customer_city,
       AVG(t.delivery_days) AS avg_delivery_days
FROM transactions t
JOIN customers c ON t.customer_id = c.customer_id
GROUP BY c.customer_city
ORDER BY avg_delivery_days;
"""
pd.read_sql(query, engine)

    customer_city  avg_delivery_days
0         Lucknow           3.234322
1            Pune           3.238099
2          Jaipur           3.239883
3          Indore           3.244195
4       Ahmedabad           3.247832
5           Surat           3.249010
6          Kanpur           3.250131
7          Nagpur           3.272876
8        Ludhiana           3.311418
9           Patna           3.334833
10  Visakhapatnam           3.339423
11     Coimbatore           3.346170
12          Kochi           3.346993
13    Bhubaneswar           3.348085
14     Chandigarh           3.355300
15        Kolkata           3.366634
16        Chennai           3.367786
17          Delhi           3.368191
18      Bengaluru           3.368834
19      Hyderabad           3.369259
20         Mumbai           3.373577
21       Vadodara           3.373944
22       Varanasi           3.405460
23        Aligarh           3.428594
24      Moradabad           3.448676
25      Gorakhpur           3.448781
26       Bareilly           3.473445
27     Saharanpur           3.491275
28      Allahabad           3.496849
29         Meerut           3.506400
30       Calcutta           3.651090
31      New Delhi           3.660622

### 12. Return Rate Analysis

In [14]:
query = """
SELECT return_status,
       COUNT(*) AS total_orders,
       ROUND(COUNT(*) * 100.0 / SUM(COUNT(*)) OVER(), 2) AS percentage
FROM transactions
GROUP BY return_status;
"""
pd.read_sql(query, engine)

  return_status  total_orders  percentage
0     Cancelled         26053        2.31
1     Delivered       1022431       90.67
2      Returned         79125        7.02

### 13. Brand Performance

In [15]:
query = """
SELECT p.brand,
       SUM(t.final_amount_inr) AS revenue
FROM transactions t
JOIN products p ON t.product_id = p.product_id
GROUP BY p.brand
ORDER BY revenue DESC
LIMIT 10;
"""
pd.read_sql(query, engine)

       brand       revenue
0    Samsung  2.062142e+10
1      Apple  1.632240e+10
2    OnePlus  1.232417e+10
3     Xiaomi  5.450159e+09
4     Realme  3.015664e+09
5       Vivo  2.348077e+09
6       Oppo  2.268237e+09
7     Lenovo  2.084388e+09
8  Alienware  1.659859e+09
9       ASUS  1.458950e+09

### 14. Customer Lifetime Value (CLV)

In [16]:
query = """
SELECT customer_id,
       SUM(final_amount_inr) AS lifetime_value
FROM transactions
GROUP BY customer_id
ORDER BY lifetime_value DESC
LIMIT 10;
"""
pd.read_sql(query, engine)

          customer_id  lifetime_value
0  CUST_2015_00003928      3757087.02
1  CUST_2016_00007974      3708826.25
2  CUST_2016_00001495      3533620.11
3  CUST_2018_00007329      3239479.72
4  CUST_2015_00009716      3134243.67
5  CUST_2020_00050279      3109580.24
6  CUST_2017_00014541      3102679.55
7  CUST_2015_00009173      3073245.76
8  CUST_2015_00002706      3026726.21
9  CUST_2015_00004117      3005482.80

### 15. Discount Effectiveness

In [23]:
query = """
SELECT 
    ROUND(discount_percent::numeric, 0) AS discount_bucket,
    AVG(final_amount_inr) AS avg_revenue
FROM transactions
GROUP BY discount_bucket
ORDER BY discount_bucket;
"""
pd.read_sql(query, engine)

    discount_bucket   avg_revenue
0               0.0  82599.020524
1               5.0  76754.637285
2               6.0  78618.693740
3               7.0  75779.937196
4               8.0  75938.315563
..              ...           ...
62             66.0  28021.062063
63             67.0  26817.394779
64             68.0  26377.436759
65             69.0  25561.197322
66             70.0  24725.279612

[67 rows x 2 columns]

### 16. Rating VS Revenue Analysis

In [18]:
query = """
SELECT p.product_rating,
       SUM(t.final_amount_inr) AS revenue
FROM transactions t
JOIN products p ON t.product_id = p.product_id
GROUP BY p.product_rating
ORDER BY p.product_rating;
"""
pd.read_sql(query, engine)

    product_rating       revenue
0              3.0  4.456235e+08
1              3.1  5.840665e+08
2              3.2  3.314049e+09
3              3.3  4.159562e+09
4              3.4  3.893172e+09
5              3.5  3.439496e+09
6              3.6  5.506579e+09
7              3.7  4.399908e+09
8              3.8  5.013589e+09
9              3.9  4.832195e+09
10             4.0  6.259635e+09
11             4.1  4.603572e+09
12             4.2  5.135636e+09
13             4.3  4.534354e+09
14             4.4  3.694816e+09
15             4.5  5.487871e+09
16             4.6  5.785063e+09
17             4.7  4.911382e+09
18             4.8  8.881601e+08

### 17. Customer Tier Analysis

In [19]:
query = """
SELECT c.customer_tier,
       COUNT(*) AS total_orders,
       SUM(t.final_amount_inr) AS revenue
FROM transactions t
JOIN customers c ON t.customer_id = c.customer_id
GROUP BY c.customer_tier
ORDER BY revenue DESC;
"""
pd.read_sql(query, engine)

  customer_tier  total_orders       revenue
0         Metro        563829  4.242541e+10
1         Tier1        338631  2.218988e+10
2         Tier2        175157  9.949852e+09
3         Rural         49992  2.323583e+09

### 18. Product Lifecycle (Year-wise sales)

In [20]:
query = """
SELECT td.order_year,
       p.product_name,
       SUM(t.final_amount_inr) AS revenue
FROM transactions t
JOIN products p ON t.product_id = p.product_id
JOIN time_dimension td ON t.order_date = td.order_date
GROUP BY td.order_year, p.product_name
ORDER BY td.order_year, revenue DESC;
"""
pd.read_sql(query, engine)

       order_year                     product_name      revenue
0            2015     Samsung Galaxy S6 16GB Black  45873171.61
1            2015        Apple iPhone 6 64GB Black  43672809.40
2            2015       Acer Gaming 8GB RAM Silver  43543997.60
3            2015  Alienware MacBook 4GB RAM Black  37368934.11
4            2015   Apple iPhone 6 Plus 64GB Black  36929936.06
...           ...                              ...          ...
11635        2025             Samsung Fitness Band     32417.69
11636        2025                    Sony Neckband     28844.17
11637        2025       Skullcandy Neckband Deluxe     28123.89
11638        2025   Audio-Technica Neckband Deluxe     19586.70
11639        2025                  OnePlus Earbuds     13155.78

[11640 rows x 3 columns]

### 19. Top Categories by Year

In [21]:
query = """
SELECT td.order_year,
       p.category,
       SUM(t.final_amount_inr) AS revenue
FROM transactions t
JOIN products p ON t.product_id = p.product_id
JOIN time_dimension td ON t.order_date = td.order_date
GROUP BY td.order_year, p.category
ORDER BY td.order_year, revenue DESC;
"""
pd.read_sql(query, engine)

    order_year     category       revenue
0         2015  Electronics  2.142163e+09
1         2016  Electronics  3.598316e+09
2         2017  Electronics  5.510026e+09
3         2018  Electronics  7.248545e+09
4         2019  Electronics  8.605901e+09
5         2020  Electronics  1.187319e+10
6         2021  Electronics  1.099021e+10
7         2022  Electronics  8.532312e+09
8         2023  Electronics  7.712999e+09
9         2024  Electronics  6.823413e+09
10        2025  Electronics  3.851650e+09

### 20. Average Order Value (AOV)

In [22]:
query = """
SELECT 
    COUNT(*) AS total_orders,
    SUM(final_amount_inr) AS total_revenue,
    AVG(final_amount_inr) AS avg_order_value
FROM transactions;
"""
pd.read_sql(query, engine)

   total_orders  total_revenue  avg_order_value
0       1127609   7.688873e+10     68187.403225